export const NORMANDALE_PROGRAMS = [
  "Associate of Arts (AA) in Liberal Education",
  "Accounting Transfer Pathway (AS)",
  "Accounting Certificate",
  "Anthropology Associate of Arts Emphasis (AA)",
  "Field Archaeology Certificate",
  "Archaeology Associate of Arts Emphasis (AA)",
  "Art Transfer Pathway (AFA)",
  "Art Associate of Arts Emphasis (AA)",
  "Biology Transfer Pathway (AS)",
  "Business Management (AAS)",
  "Business Software and Administrative Management (AAS)",
  "Business Software and Administrative Management Certificate",
  "Business Transfer Pathway (AS)",
  "Chemistry Transfer Pathway (AS)",
  "Communication Studies Transfer Pathway (AA)",
  "Community Health Worker Navigator Certificate",
  "Computer Science Transfer Pathway (AS)",
  "Computer Technology (AAS)",
  "Computer Technology Certificate",
  "Creative Writing (AFA)",
  "Creative Writing Certificate",
  "Criminal Justice Transfer Pathway (AS)",
  "Data Analytics (AS)",
  "Dental Hygiene (AS)",
  "Economics Transfer Pathway (AA)",
  "Elementary Education Foundations Transfer Pathway (AS)",
  "Engineering Broad Field (AS)",
  "English Transfer Pathway (AA)",
  "Exercise Science Transfer Pathway (AS)",
  "Exercise Specialist Certificate",
  "Family Studies Certificate",
  "Food and Beverage Management Certificate",
  "Food Science (AS)",
  "French Associate of Arts Emphasis (AA)",
  "Geography Associate of Arts Emphasis (AA)",
  "German Associate of Arts Emphasis (AA)",
  "Health Science Broad Field (AS)",
  "Healthcare Systems Technology (AAS)",
  "History Transfer Pathway (AA)",
  "Hospitality and Tourism Management (AAS)",
  "Hotel Operations Management Certificate",
  "Human Resource Management Certificate",
  "Individualized Studies (AS)",
  "International Experience Certificate",
  "Management Certificate",
  "Marketing Certificate",
  "Mathematics Transfer Pathway (AA)",
  "Music (AFA)",
  "Professional Nursing (AS)",
  "Nursing Assistant Certificate",
  "Peace Officer / Public Safety Transfer Pathway (AS)",
  "Peace Officer Certificate",
  "Philosophy Associate of Arts Emphasis (AA)",
  "Physics Associate of Arts Emphasis (AA)",
  "Political Science Transfer Pathway (AA)",
  "Psychology Transfer Pathway (AA)",
  "Public Health (AS)",
  "Religious Studies Certificate",
  "Small Business Management Certificate",
  "Sociology Transfer Pathway (AA)",
  "Spanish Transfer Pathway (AA)",
  "Spanish Certificate",
  "Special Education Foundations Transfer Pathway (AS)",
  "Sustainable Tourism Management Certificate",
  "Theatre Performance Transfer Pathway (AFA)",
  "Theatre Production and Design Transfer Pathway (AFA)",
  "Vacuum and Thin Film Technology (AAS)",
  "Vacuum Maintenance Technician Certificate",
  "Vacuum Technology Certificate",
  "Women's Studies Associate of Arts Emphasis (AA)"
] as const;
